"""Exact audit of the rank-3 (t=4, s=3) weighted-kernel group.

This is deliberately a diagnostic, not a theorem certificate.  It rebuilds
the depth-bounded integral return set with Fraction/integer arithmetic, checks
the reported congruence image sizes, and computes finite orbits of unimodular
vectors modulo small levels.  The latter are only local evidence: they do not
classify rational boundary flags or prove that the true positive macro group
equals the subgroup generated by the sampled returns.
"""

from collections import deque
from math import gcd
import argparse

from explore_weighted_kernel_group import (
    determinant_integer,
    exchange_matrix,
    explore_fast,
    identity,
    inverse_mod,
    multiply_mod,
)


def matrix_mod(matrix, modulus):
    return tuple(tuple(value % modulus for value in row) for row in matrix)


def image_generators(matrices, modulus):
    gens = {matrix_mod(matrix, modulus) for matrix in matrices}
    # All supplied matrices have determinant +1, so inverses exist modulo every
    # tested level.  Adding inverses computes the group generated by the sample.
    gens |= {inverse_mod(matrix, modulus) for matrix in gens}
    return tuple(gens)


def finite_image(matrices, modulus):
    gens = image_generators(matrices, modulus)
    size = len(gens[0])
    start = tuple(tuple(int(row == col) for col in range(size))
                  for row in range(size))
    seen = {start}
    queue = deque([start])
    while queue:
        current = queue.popleft()
        for generator in gens:
            output = multiply_mod(generator, current, modulus)
            if output not in seen:
                seen.add(output)
                queue.append(output)
    return seen


def rational_matrix_mod(matrix, modulus):
    return tuple(tuple(value.numerator * pow(value.denominator, -1, modulus)
                        % modulus for value in row) for row in matrix)


def burau_adjacent_image(modulus):
    """Finite GL image of the three adjacent Burau matrices, when tractable."""
    weights = (27, 9, 3, 1)
    adjacent = [rational_matrix_mod(
        exchange_matrix(weights, index, index + 1), modulus)
                for index in range(3)]
    generators = tuple(adjacent) + tuple(inverse_mod(matrix, modulus)
                                         for matrix in adjacent)
    size = 3
    start = tuple(tuple(int(row == col) for col in range(size))
                  for row in range(size))
    seen = {start}
    queue = deque([start])
    while queue:
        current = queue.popleft()
        for generator in generators:
            output = multiply_mod(generator, current, modulus)
            if output not in seen:
                seen.add(output)
                queue.append(output)
    return seen


def vector_action(matrix, vector, modulus):
    return tuple(sum(matrix[row][col] * vector[col]
                     for col in range(len(vector))) % modulus
                 for row in range(len(vector)))


def unit_vector(vector, modulus):
    """Canonical representative of a projective unimodular vector.

    Over a prime this is the usual first-nonzero-coordinate normalization.  For
    composite levels we only quotient by units; this is enough for the local
    orbit diagnostic and avoids silently identifying non-unimodular vectors.
    """
    if all(value % modulus == 0 for value in vector):
        return None
    if gcd(*(value for value in vector), modulus) != 1:
        return None
    units = [value for value in range(modulus) if gcd(value, modulus) == 1]
    candidates = []
    for unit in units:
        candidates.append(tuple(unit * value % modulus for value in vector))
    return min(candidates)


def projective_orbit(image, modulus, seed=(1, 0, 0)):
    start = unit_vector(seed, modulus)
    seen = {start}
    queue = deque([start])
    while queue:
        current = queue.popleft()
        for matrix in image:
            output = unit_vector(vector_action(matrix, current, modulus),
                                 modulus)
            if output is None:
                continue
            if output not in seen:
                seen.add(output)
                queue.append(output)
    return seen


def projective_lines(modulus):
    lines = set()
    for first in range(modulus):
        for second in range(modulus):
            for third in range(modulus):
                line = unit_vector((first, second, third), modulus)
                if line is not None:
                    lines.add(line)
    return lines


def projective_orbits(image, modulus):
    remaining = projective_lines(modulus)
    result = []
    while remaining:
        seed = min(remaining)
        orbit = projective_orbit(image, modulus, seed)
        result.append(orbit)
        remaining -= orbit
    return result


def report(depth):
    returns = explore_fast((27, 9, 3, 1), depth)
    positive = [matrix for matrix in returns
                if determinant_integer(matrix) == 1]
    print(f"depth={depth} primitive_returns={len(returns)} det_plus_one={len(positive)}")
    for modulus in (2, 3, 4, 5, 8):
        image = finite_image(positive, modulus)
        orbit = projective_orbit(image, modulus)
        print(f"mod {modulus}: image={len(image)} unimodular_projective_orbit={len(orbit)}")
    for modulus in (2, 5, 7):
        image = burau_adjacent_image(modulus)
        orbits = projective_orbits(image, modulus)
        print(f"adjacent Burau mod {modulus}: GL image={len(image)} "
              f"P2-orbits={sorted(len(orbit) for orbit in orbits)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--depth", type=int, default=8)
    report(parser.parse_args().depth)
