"""Explore return groups generated by unequal power-block exchanges."""

from collections import deque
from fractions import Fraction as F
from itertools import combinations
from math import gcd


def identity(size):
    return tuple(tuple(F(row == column) for column in range(size))
                 for row in range(size))


def multiply(left, right):
    size = len(left)
    return tuple(tuple(sum(left[row][k] * right[k][column]
                           for k in range(size))
                       for column in range(size))
                 for row in range(size))


def primitive(matrix):
    denominator = 1
    for row in matrix:
        for value in row:
            denominator = denominator * value.denominator // gcd(denominator,
                                                                   value.denominator)
    entries = [int(value * denominator) for row in matrix for value in row]
    content = gcd(*(abs(value) for value in entries))
    entries = [value // content for value in entries]
    first = next(value for value in entries if value)
    if first < 0:
        entries = [-value for value in entries]
    size = len(matrix)
    return tuple(tuple(entries[size * row:size * (row + 1)])
                 for row in range(size))


def determinant(matrix):
    values = [[F(value) for value in row] for row in matrix]
    result = F(1)
    for column in range(len(values)):
        pivot = next((row for row in range(column, len(values))
                      if values[row][column]), None)
        if pivot is None:
            return F(0)
        if pivot != column:
            values[pivot], values[column] = values[column], values[pivot]
            result *= -1
        value = values[column][column]
        result *= value
        for row in range(column + 1, len(values)):
            scale = values[row][column] / value
            for index in range(column, len(values)):
                values[row][index] -= scale * values[column][index]
    return result


def exchange_matrix(weights, large, small):
    assert weights[large] > weights[small]
    size = len(weights) - 1
    full = [list(row) for row in identity(len(weights))]
    ratio = F(weights[small], weights[large])
    full[large] = [F(0) for _ in weights]
    full[large][large] = 1 - ratio
    full[large][small] = ratio
    full[small] = [F(0) for _ in weights]
    full[small][large] = 1

    # Parameterize the weighted zero-sum hyperplane by the first size values.
    result = []
    for row in range(size):
        coefficients = full[row][:size]
        last = full[row][size]
        result.append(tuple(coefficients[column]
                            - last * F(weights[column], weights[size])
                            for column in range(size)))
    return tuple(result)


def generators(weights):
    result = {}
    for left, right in combinations(range(len(weights)), 2):
        large, small = ((left, right) if weights[left] > weights[right]
                        else (right, left))
        if weights[large] == weights[small]:
            continue
        result[f"{large}{small}"] = exchange_matrix(weights, large, small)
    return result


def explore(weights, depth):
    basic = generators(weights)
    start = identity(len(weights) - 1)
    seen = {primitive(start): ""}
    frontier = [(start, "")]
    integral = {}
    for level in range(1, depth + 1):
        following = []
        for matrix, word in frontier:
            for letter, generator in basic.items():
                output = multiply(generator, matrix)
                key = primitive(output)
                if key in seen:
                    continue
                output_word = word + "." + letter
                seen[key] = output_word
                following.append((output, output_word))
                det = determinant(key)
                if abs(det) == 1:
                    integral[key] = output_word
        frontier = following
        print("weights", weights, "depth", level, "states", len(seen),
              "integral", len(integral), flush=True)
    return integral


def multiply_integer(left, right):
    size = len(left)
    values = [[sum(left[row][k] * right[k][column] for k in range(size))
               for column in range(size)] for row in range(size)]
    content = gcd(*(abs(value) for row in values for value in row))
    values = [[value // content for value in row] for row in values]
    first = next(value for row in values for value in row if value)
    if first < 0:
        values = [[-value for value in row] for row in values]
    return tuple(tuple(row) for row in values)


def determinant_integer(matrix):
    if len(matrix) != 3:
        return int(determinant(matrix))
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    return (a * (e * i - f * h) - b * (d * i - f * g)
            + c * (d * h - e * g))


def explore_fast(weights, depth):
    basic = {letter: primitive(matrix)
             for letter, matrix in generators(weights).items()}
    size = len(weights) - 1
    start = tuple(tuple(int(row == column) for column in range(size))
                  for row in range(size))
    seen = {start: ""}
    frontier = [start]
    integral = {}
    for level in range(1, depth + 1):
        following = []
        for matrix in frontier:
            word = seen[matrix]
            for letter, generator in basic.items():
                output = multiply_integer(generator, matrix)
                if output in seen:
                    continue
                output_word = word + "." + letter
                seen[output] = output_word
                following.append(output)
                if abs(determinant_integer(output)) == 1:
                    integral[output] = output_word
        frontier = following
        print("FAST weights", weights, "depth", level, "states", len(seen),
              "integral", len(integral), flush=True)
    return integral


def multiply_mod(left, right, modulus):
    size = len(left)
    return tuple(tuple(sum(left[row][k] * right[k][column]
                           for k in range(size)) % modulus
                       for column in range(size))
                 for row in range(size))


def inverse_mod(matrix, modulus):
    size = len(matrix)
    augmented = [list(matrix[row]) + [int(row == column)
                                      for column in range(size)]
                 for row in range(size)]
    for column in range(size):
        pivot = next(row for row in range(column, size)
                     if gcd(augmented[row][column], modulus) == 1)
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        inverse = pow(augmented[column][column], -1, modulus)
        augmented[column] = [value * inverse % modulus
                             for value in augmented[column]]
        for row in range(size):
            if row == column:
                continue
            scale = augmented[row][column]
            augmented[row] = [(left - scale * right) % modulus
                              for left, right in zip(augmented[row],
                                                     augmented[column])]
    return tuple(tuple(row[size:]) for row in augmented)


def image_size(matrices, modulus):
    generators_mod = {tuple(tuple(value % modulus for value in row)
                            for row in matrix) for matrix in matrices}
    generators_mod |= {inverse_mod(matrix, modulus)
                       for matrix in list(generators_mod)}
    start = identity(len(next(iter(matrices))))
    start = tuple(tuple(int(value) for value in row) for row in start)
    seen = {start}
    queue = deque([start])
    while queue:
        current = queue.popleft()
        for generator in generators_mod:
            following = multiply_mod(generator, current, modulus)
            if following not in seen:
                seen.add(following)
                queue.append(following)
    return len(seen)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--depth", type=int, default=7)
    arguments = parser.parse_args()
    integral = explore((27, 9, 3, 1), arguments.depth)
    positive = [matrix for matrix in integral if determinant(matrix) == 1]
    print("SL generators", len(positive))
    for prime in (2, 3, 5, 7):
        print("mod", prime, "image", image_size(positive, prime), flush=True)
